import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//

import React from "react";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata = {
  title: "Shoply — Modern E-Commerce",
  description:
    "A sleek, minimalistic Next.js frontend for a Django e-commerce backend",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#0B0F19] text-[#E6E8EB] antialiased">
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID as string}
        >
          <div className="max-w-6xl mx-auto px-6 py-10 flex flex-col min-h-screen">
            {children}
          </div>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
