# Generated by Django 5.2.1 on 2025-06-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('resource', models.CharField(choices=[('shared', 'Shared'), ('events', 'Events'), ('blog', 'Blog')], default='shared', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
