# Generated by Django 5.2.1 on 2025-10-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='resource',
        ),
    ]
