# Generated by Django 5.2.1 on 2025-07-12 20:49

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=150, null=True)),
        ),
    ]
