# Generated by Django 5.2.1 on 2025-10-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
